// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taokfccvbqfcgsikgtmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhb2tmY2N2YnFmY2dzaWtndG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTY5NjMsImV4cCI6MjA1OTIzMjk2M30.dVSEFPNnstEthZE5-cE5zhIazaJEK1GxQSoeZLOEmCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);